name: Deploy to UBA-DEV (Docker Compose)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker tag to deploy (e.g., v1.0.4)'
        required: true
        default: 'latest'

jobs:
  deploy_on_uba_dev:
    runs-on: ubuntu-latest
    environment: UBA-DEV

    steps:
      # Step 1: Set the image URI
      - name: Set IMAGE_URI
        run: |
          IMAGE_URI="ghcr.io/psmri/ubi-strapi-provider:${{ github.event.inputs.tag }}"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "📦 Deploying image: $IMAGE_URI"

      # Step 2: SSH into server and update Compose service
      - name: Deploy via Docker Compose
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            echo "🚀 Starting deployment to UBA-DEV environment"

            BASE_DIR="${{ secrets.TARGET_DIR }}"
            IMAGE_URI="${{ env.IMAGE_URI }}"

            cd "$BASE_DIR"

            echo "🔐 Logging in to GHCR..."
            echo "${{ secrets.GHCR_PAT_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

            echo "📦 Pulling new image..."
            docker pull "$IMAGE_URI"

            echo "🛑 Updating Docker Compose service..."
            docker-compose stop ubi-strapi-provider || true
            docker-compose rm -f ubi-strapi-provider || true

            # Update image in docker-compose.yml dynamically
            sed -i "s|image:.*|image: $IMAGE_URI|" docker-compose.yml

            echo "🚀 Starting service via Docker Compose..."
            docker-compose up -d

            echo "✅ Deployment complete!"
            docker ps | grep ubi-strapi-provider

      # Step 3: Slack notification
      - name: Notify on Slack
        uses: iRoachie/slack-github-actions@v2.3.2
        if: ${{ always() }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
