name: Deploy to UBA-DEPWD-PILOT

on:
  push:
    branches:
      - main

jobs:
  deploy_strapi:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: UBA-DEPWD-PILOT
    steps:
      - name: Deploy Strapi based Catalog Manager for Provider
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PILOT }}
          username: ${{ secrets.SSH_USERNAME_PILOT }}
          key: ${{ secrets.SSH_KEY_PILOT }}
          port: ${{ secrets.SSH_PORT_PILOT }}
          script: |
            cd ${{ secrets.TARGET_DIR_PILOT }}
            if [ -f .env ]; then
              rm .env
            fi
            echo "${{ secrets.ENV_PILOT }}" > .env
            ls -ltra
            ./deploy.sh

      ## Notify on Slack
      - name: Notify on Slack channel
        uses: iRoachie/slack-github-actions@v2.3.2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
        if: ${{ always() }}
